apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /backend-api(/|$)(.*)
      #- path: /
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 5000