# Configure global settings in this section.
global:
  name: consul
  # Bootstrap ACLs within Consul. This is highly recommended.
#   acls:
#     manageSystemACLs: true
  # Gossip encryption
#   gossipEncryption:
#     autoGenerate: true
# Configure your Consul servers in this section.
server:
  # Specify 1 Consul cluster.
  replicas: 1
  # Specify the resources that servers request for placement. These values will serve a large environment.
#   resources:
#     requests:
#       memory: '32Gi'
#       cpu: '4'
#       disk: '50Gi'
#     limits:
#       memory: '32Gi'
#       cpu: '4'
#       disk: '50Gi'
  # If using Enterprise, reference the Kubernetes secret that holds your license here
#   enterpriseLicense:
#     secretName: 'consul-license'
#     secretKey: 'key'
# Configure Consul clients in this section
# client:
#   # Specify the resources that clients request for deployment.
#   resources:
#     requests:
#       memory: '8Gi'
#       cpu: '2'
#       disk: '15Gi'
#     limits:
#       memory: '8Gi'
#       cpu: '2'
#       disk: '15Gi'
# Enable and configure the Consul UI.
ui:
  enabled: true
# Enable Consul connect pod injection
connectInject:
  enabled: true
  default: true
controller:
  enabled: true

