apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: db
        app: db
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "root"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "example"
        name: db
        image: docker.io/mongo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
          name: tcp
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
    